version: "1"

services:
  - type: web
    name: firstread-document-agent
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && cd docgen && python manage.py collectstatic --noinput && python manage.py migrate
    startCommand: cd docgen && daphne -b 0.0.0.0 -p $PORT docgen.asgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: docgen.settings
      - key: PYTHONPATH
        value: /opt/render/project/src
      # - key: DATABASE_URL
      #   fromDatabase:
      #     name: postgres
      #     property: connectionString
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: "*"

# databases:
#   - name: postgres
#     databaseName: firstread_db
#     user: firstread_user
#     plan: free